name = "HOLean"
version = "0.1.0"
defaultTargets = ["holean", "Examples"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"

[[lean_lib]]
name = "HOLean"

[[lean_lib]]
name = "Examples"
globs = ["Examples.+"]

[[lean_exe]]
name = "holean"
root = "Main"
